skeleton/server/models.py
# Copyright 2016 Cisco Systems, Inc.
# All rights reserved.

import datetime

from skeleton.server import app, db, bcrypt


class User(db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(255), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)

    def __init__(self, email, password, admin=False):
        self.email = email
        self.password = bcrypt.generate_password_hash(
            password, app.config.get('BCRYPT_LOG_ROUNDS')
        )
        self.registered_on = datetime.datetime.now()
        self.admin = admin

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return '<User {0}>'.format(self.email)

skeleton/server/user/forms.py
# Copyright 2016 Cisco Systems, Inc.
# All rights reserved.

from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo


class LoginForm(Form):
    email = StringField('Email Address', [DataRequired(), Email()])
    password = PasswordField('Password', [DataRequired()])


class RegisterForm(Form):
    email = StringField(
        'Email Address',
        validators=[DataRequired(), Email(message=None), Length(min=6, max=40)])
    password = PasswordField(
        'Password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Confirm password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

skeleton/server/__init__.py
# Copyright 2016 Cisco Systems, Inc.
# All rights reserved.

import os

from flask import Flask, render_template
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_debugtoolbar import DebugToolbarExtension
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy


app = Flask(
    __name__,
    template_folder='../client/templates',
    static_folder='../client/static'
)

app_settings = os.getenv('APP_SETTINGS', 'skeleton.server.config.DevelopmentConfig')
app.config.from_object(app_settings)

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
toolbar = DebugToolbarExtension(app)
bootstrap = Bootstrap(app)
db = SQLAlchemy(app)

from skeleton.server.user.views import user_blueprint
from skeleton.server.main.views import main_blueprint
app.register_blueprint(user_blueprint)
app.register_blueprint(main_blueprint)

from skeleton.server.models import User

login_manager.login_view = "user.login"
login_manager.login_message_category = 'danger'


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


@app.errorhandler(401)
def forbidden_page_401(error):
    return render_template("errors/401.html"), 401


@app.errorhandler(403)
def forbidden_page_403(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

skeleton/server/main/views.py
# Copyright 2016 Cisco Systems, Inc.
# All rights reserved.

from flask import render_template, Blueprint

main_blueprint = Blueprint('main', __name__,)


@main_blueprint.route('/')
def home():
    return render_template('main/home.html')


@main_blueprint.route("/about/")
def about():
    return render_template("main/about.html")

skeleton/server/user/views.py
# Copyright 2016 Cisco Systems, Inc.
# All rights reserved.


from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask_login import login_user, logout_user, login_required

from skeleton.server import bcrypt, db
from skeleton.server.models import User
from skeleton.server.user.forms import LoginForm, RegisterForm

user_blueprint = Blueprint('user', __name__,)


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()

        login_user(user)

        flash('Thank you for registering.', 'success')
        return redirect(url_for("user.members"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('user.members'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', title='Please Login', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/members')
@login_required
def members():
    return render_template('user/members.html')

skeleton/client/templates/_base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>Flask Skeleton{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.1/yeti/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>

  <body>

    {% include 'header.html' %}

    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
             {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}


        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    <br><br>

    {% include 'footer.html' %}

    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.2.min.js" type="text/javascript"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

skeleton/client/templates/footer.html
<footer>
  <div class="container">
    <small>
      <span>© <a href="mailto:xiaoquwl@gmail.com">GitLab Demo</a></span>
    </small>
  </div>
</footer>

skeleton/client/templates/header.html
<header class="site-header">
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <a class="navbar-brand" href="{{ url_for('main.home') }}">Flask-Skeleton</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{{ url_for('main.about') }}">About</a></li>
          {% if current_user.is_authenticated %}
           <li><a href="{{ url_for('user.members') }}">Members</a></li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
          {% else %}
            <li><a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;Register/Login</a></li>
          {% endif %}
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>
</header>

skeleton/client/templates/main/about.html
{% extends "_base.html" %}

{% block content %}

<div class="body-content">
  <div class="row">
    <h1>About</h1>
  </div>
</div>

{% endblock %}

skeleton/client/templates/main/home.html
{% extends "_base.html" %}

{% block content %}

<div class="body-content">
  <div class="row">
    <h1>Welcome!</h1>
  </div>
</div>

{% endblock %}

skeleton/client/templates/user/login.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

  <header class="content-header">
    <h1>Please login</h1>
  </header>

  <br>


  <form class="form" role="form" method="post" action="">

    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}


    <div class="col-lg-4 col-sm-4">

      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}

      <button class="btn btn-success" type="submit">Sign In!</button>
      <br><br>
      <p>Need to <a href="{{ url_for('user.register') }}">Register</a>?</p>
    </div>

  </form>


{% endblock content %}

skeleton/client/templates/user/members.html
{% extends "_base.html" %}
{% block content %}
  <h1>Welcome, <em>{{ current_user.email }}</em>!</h1>
  <h3>This is the members-only page :)</h3>
{% endblock %}

skeleton/client/templates/user/register.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

  <header class="content-header">
    <h1>Please Register</h1>
  </header>

  <br>


  <form class="form" role="form" method="post" action="">

    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}


    <div class="col-lg-4 col-sm-4">

      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}
      {{ wtf.form_field(form.confirm) }}

      <button class="btn btn-success" type="submit">Register!</button>
      <br><br>
      <p>Already have an account? <a href="{{ url_for('user.login') }}">Sign in</a>.</p>

    </div>

  </form>


{% endblock content %}